import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import ThemeSwitch from '@/components/navbar/themeSwitcher'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rest-Countries',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <ThemeSwitch/> */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
